theme:
  routes:
    - path: /
      component: pages/home

  noMatch:
    component: pages/404

routes:
  - path: /doge
    component: pages/magic-img
  - path: /nyancat
    component: pages/magic-img
